### ISSUE TITLE
Missing `@types/unist` in package.json dependencies

### ISSUE THREAD

**Issue by alvinleung1996** [syntax-tree/mdast-util-directive#3]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-directive 2.1.1

### Steps to reproduce

When using Yarn with strict PnP mode, `complex-types.d.ts` cannot import `unist` because `@types/unist` is not explicitly listed in the package.json dependencies field. This causes the interfaces `TextDirective`, `LeafDirective` and `ContainerDirective` to be incomplete because they cannot resolve the parent interface `Parent` from `unist`.

### Expected behavior

`@types/unist` is explicitly listed in the package.json dependencies field.

### Actual behavior

`@types/unist` is not explicitly listed in the package.json dependencies field.

### Runtime

Node v16

### Package manager

Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
👍 PR welcome!
