### ISSUE TITLE
cant parse into containerDirective

### ISSUE THREAD

**Issue by mumu1993** [syntax-tree/mdast-util-directive#5]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-directive@2.2.2 micromark-extension-directive@2.1.1

### Steps to reproduce

string like this
:::tip Note\nWhen you select **Vulkan** as Graphics APIs, the Unity Editor version should be 2020.3.13 or later.\n:::
cant parse into containerDirective

but when i delete the first space like this

:::tipNote\nWhen you select **Vulkan** as Graphics APIs, the Unity Editor version should be 2020.3.13 or later.\n:::
this can parse into containerDirective

### Expected behavior

:::tip Note\nWhen you select **Vulkan** as Graphics APIs, the Unity Editor version should be 2020.3.13 or later.\n:::
this string can be parsed into containerDirective

### Actual behavior

:::tip Note\nWhen you select **Vulkan** as Graphics APIs, the Unity Editor version should be 2020.3.13 or later.\n:::
this string cant parsed into containerDirective

### Affected runtime and version

mdast-util-directive@2.2.2 micromark-extension-directive@2.1.1

**Comment by wooorm** [comment]
Please use markdown code to show your code, I can’t read this

**Comment by wooorm** [comment]
Closing due to no response, I don’t know what you mean.
